### ISSUE TITLE
Consider retiring this repository or make it private

### ISSUE THREAD

**Issue by BrainCrumbz** [slashdotdash/stateless#5]
Hi

is this repo a(n old) clone of https://github.com/dotnet-state-machine/stateless ? If that's the case, it seems a little confusing for people googling around and looking for original repo.

Thoughts? 
Regards

**Comment by slashdotdash** [comment]
Yes, it was originally cloned from Google code, before it existed on GitHub. 

I have added a [DEPRECATED] tag and link to the official repo.

Done via d59d4e3966ffac30674e66726d2636c5e09e846b.

**Comment by BrainCrumbz** [comment]
Wow, that was quick! Cool!
